ArkNet::ArkNetApi
List<Tuple<string, int> > ArkNet.ArkNetApi._peerSeedListMainNet
Initial Seeds for the MainNet
Referenced by ArkNet.ArkNetApi.GetInitialPeer.
List<Tuple<string, int> > ArkNet.ArkNetApi._peerSeedListDevNet
Initial Seeds for the DevNet
readonly Lazy<ArkNetApi> ArkNet.ArkNetApi._lazy
Lazy Load of the API, calls to
ArkNetApi ArkNet.ArkNetApi.Instance
Instanciate the API Called through to allow lazy load of the API.
Referenced by ArkNet.Core.TransactionApi.CreateDelegate, ArkNet.Core.TransactionApi.createSecondSignature, ArkNet.Core.TransactionApi.CreateTransaction, ArkNet.Core.TransactionApi.CreateVote, ArkNetTest.Tests.TransactionCryptoTests.GetAddressTest, ArkNet.Controller.AccountController.GetArkAccount, ArkNet.Controller.AccountController.GetArkAccountAsync, ArkNet.Core.PeerApi.MakeRequestInternal, ArkNet.Core.PeerApi.PeerApi, ArkNet.Core.NetworkApi.SetPeerList.
ArkNetworkSettings ArkNet.ArkNetApi.NetworkSettings
Store the network settings.
Referenced by ArkNet.Core.TransactionApi.CreateDelegate, ArkNet.Core.TransactionApi.createSecondSignature, ArkNet.Core.TransactionApi.CreateTransaction, ArkNet.Core.TransactionApi.CreateVote, ArkNetTest.Tests.TransactionCryptoTests.GetAddressTest, ArkNet.Controller.AccountController.GetArkAccount, ArkNet.Controller.AccountController.GetArkAccountAsync, ArkNet.Core.PeerApi.MakeRequestInternal, ArkNet.Core.PeerApi.PeerApi, ArkNet.Core.NetworkApi.SetPeerList.
ArkNet.ArkNetApi.ArkNetApi()
Prevents a default instance of the ArkNetApi class from being created.
async Task ArkNet.ArkNetApi.SetNetworkSettings(PeerApi initialPeer)
Fetch the the NetworkSettings, and set the NetworkSettings variable, which is used for every subsequent request after the initial ones.
initialPeer Initial Peer from which the settings are fetched. Instiate a based on the initial peer provided.
References ArkNet.Core.PeerApi.Ip, ArkNet.Core.PeerApi.Port, ArkNet.Utils.ArkNetworkSettings.Version.
Referenced by ArkNet.ArkNetApi.Start.
PeerApi ArkNet.ArkNetApi.GetInitialPeer(string initialPeerIp, int initialPeerPort)
Get the initial peers to connect to the blockchain.
initialPeerIp Ip of the first peer. initialPeerPort Port that the first peer listen on. Return the first peer found at the IP/Port given.
Referenced by ArkNet.ArkNetApi.GetInitialPeer, ArkNet.ArkNetApi.Start.
async Task<PeerApi> ArkNet.ArkNetApi.GetInitialPeer(NetworkType type, int retryCount=0)
Is needed to fetch the peer.
type Can be : DevNet (test), ask Dark (testnet coins) on the slack. MainNet (live, beware real money, financial loss possible there). retryCount Number of retry before a timeout Returns the first that is online
References ArkNet.ArkNetApi._peerSeedListMainNet, ArkNet.ArkNetApi.GetInitialPeer.
async Task ArkNet.ArkNetApi.Start(NetworkType type)
Start the Network
type Can be : DevNet (test), ask Dark (testnet coins) on the slack. MainNet (live, beware real money, financial loss possible there). The starts the node.
References ArkNet.ArkNetApi.GetInitialPeer, ArkNet.ArkNetApi.SetNetworkSettings.
async Task ArkNet.ArkNetApi.Start(string initialPeerIp, int initialPeerPort)
Start the Network.
initialPeerIp The Initial peer's IP initialPeerPort The Initial Peer's Port The starts the node.
References ArkNet.ArkNetApi.GetInitialPeer, ArkNet.ArkNetApi.SetNetworkSettings.