ArkNet::Utils::ByteBuffer
byte [] ArkNet.Utils.ByteBuffer.hb
bool ArkNet.Utils.ByteBuffer.bigEndian
int ArkNet.Utils.ByteBuffer.offset
bool ArkNet.Utils.ByteBuffer.isReadOnly
sealed override bool ArkNet.Utils.ByteBuffer.HasArray
override object ArkNet.Utils.ByteBuffer.Array
override int ArkNet.Utils.ByteBuffer.ArrayOffset
abstract override bool ArkNet.Utils.ByteBuffer.IsDirect
Referenced by ArkNet.Utils.ByteBuffer.HeapByteBuffer.Put.
ByteOrder ArkNet.Utils.ByteBuffer.Order
ArkNet.Utils.ByteBuffer.ByteBuffer(int mark, int pos, int lim, int cap, byte[] hb, int offset)
Creates a new buffer with the given mark, position, limit, capacity, backing array, and array offset
ArkNet.Utils.ByteBuffer.ByteBuffer(int mark, int pos, int lim, int cap)
Creates a new buffer with the given mark, position, limit, and capacity
abstract byte ArkNet.Utils.ByteBuffer._get(int i)
abstract void ArkNet.Utils.ByteBuffer._put(int i, byte b)
static ByteBuffer ArkNet.Utils.ByteBuffer.AllocateDirect(int capacity)
Allocates a new direct byte buffer. (NOT IMPLEMENTED IN LUCENE.NET)
The new buffer's position will be zero, its limit will be its capacity, its mark will be undefined, and each of its elements will be initialized to zero.Whether or not it has a backing array is unspecified. capacity The new buffer's capacity, in bytes The new byte buffer ArgumentException If the capacity is a negative integer
static ByteBuffer ArkNet.Utils.ByteBuffer.Allocate(int capacity)
Allocates a new byte buffer.
The new buffer's position will be zero, its limit will be its capacity, its mark will be undefined, and each of its elements will be initialized to zero.It will have a backing array and its array offset will be zero. capacity The new buffer's capacity, in bytes The new byte buffer ArgumentException If the capacity is a negative integer
static ByteBuffer ArkNet.Utils.ByteBuffer.Wrap(byte[] array, int offset, int length)
Wraps a byte array into a buffer.
The new buffer will be backed by the given byte array; that is, modifications to the buffer will cause the array to be modified and vice versa. The new buffer's capacity will be array.Length, its position will be offset , its limit will be offset + length, and its mark will be undefined. Its backing array will be the given array, and its array offset will be zero. array The array that will back the new buffer offset The offset of the subarray to be used; must be non-negative and no larger than array.length. The new buffer's position will be set to this value. length The length of the subarray to be used; must be non-negative and no larger than array.Length - Offset. The new buffer's limit will be set to Offset + Length. The new byte buffer ArgumentOutOfRangeException If the preconditions on the offset and length parameters do not hold
static ByteBuffer ArkNet.Utils.ByteBuffer.Wrap(byte[] array)
Wraps a byte array into a buffer.
The new buffer will be backed by the given byte array; that is, modifications to the buffer will cause the array to be modified and vice versa. The new buffer's capacity will be array.Length, its position will be offset , its limit will be offset + length, and its mark will be undefined. Its backing array will be the given array, and its array offset will be zero. array The array that will back this buffer The new byte buffer
abstract ByteBuffer ArkNet.Utils.ByteBuffer.Slice()
Creates a new byte buffer whose content is a shared subsequence of this buffer's content.
The content of the new buffer will start at this buffer's current position. Changes to this buffer's content will be visible in the new buffer, and vice versa; the two buffers' position, limit, and mark values will be independent.The new buffer's position will be zero, its capacity and its limit will be the number of bytes remaining in this buffer, and its mark will be undefined. The new buffer will be direct if, and only if, this buffer is direct, and it will be read-only if, and only if, this buffer is read-only. The new byte buffer
abstract ByteBuffer ArkNet.Utils.ByteBuffer.Duplicate()
Creates a new byte buffer that shares this buffer's content.
The content of the new buffer will be that of this buffer. Changes to this buffer's content will be visible in the new buffer, and vice versa; the two buffers' position, limit, and mark values will be independent. The new buffer's capacity, limit, position, and mark values will be identical to those of this buffer. The new buffer will be direct if, and only if, this buffer is direct, and it will be read-only if, and only if, this buffer is read-only. The new byte buffer
abstract ByteBuffer ArkNet.Utils.ByteBuffer.AsReadOnlyBuffer()
abstract byte ArkNet.Utils.ByteBuffer.Get()
Referenced by ArkNet.Utils.ByteBuffer.CompareTo, ArkNet.Utils.ByteBuffer.Equals, ArkNet.Utils.ByteBuffer.Put.
abstract ByteBuffer ArkNet.Utils.ByteBuffer.Put(byte b)
abstract byte ArkNet.Utils.ByteBuffer.Get(int index)
abstract ByteBuffer ArkNet.Utils.ByteBuffer.Put(int index, byte b)
virtual ByteBuffer ArkNet.Utils.ByteBuffer.Get(byte[] dst, int offset, int length)
virtual ByteBuffer ArkNet.Utils.ByteBuffer.Get(byte[] dst)
virtual ByteBuffer ArkNet.Utils.ByteBuffer.Put(ByteBuffer src)
References ArkNet.Utils.ByteBuffer.Get.
virtual ByteBuffer ArkNet.Utils.ByteBuffer.Put(byte[] src, int offset, int length)
ByteBuffer ArkNet.Utils.ByteBuffer.Put(byte[] src)
abstract ByteBuffer ArkNet.Utils.ByteBuffer.Compact()
override string ArkNet.Utils.ByteBuffer.ToString()
override int ArkNet.Utils.ByteBuffer.GetHashCode()
override bool ArkNet.Utils.ByteBuffer.Equals(object obj)
References ArkNet.Utils.ByteBuffer.Get, ArkNet.Utils.Buffer.Limit, ArkNet.Utils.Buffer.Remaining.
int ArkNet.Utils.ByteBuffer.CompareTo(ByteBuffer other)
References ArkNet.Utils.ByteBuffer.Get, ArkNet.Utils.Buffer.Position.
abstract char ArkNet.Utils.ByteBuffer.GetChar()
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutChar(char value)
abstract char ArkNet.Utils.ByteBuffer.GetChar(int index)
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutChar(int index, char value)
abstract short ArkNet.Utils.ByteBuffer.GetInt16()
NOTE: This was getShort() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt16(short value)
NOTE: This was putShort() in the JDK
abstract short ArkNet.Utils.ByteBuffer.GetInt16(int index)
NOTE: This was getShort() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt16(int index, short value)
NOTE: This was putShort() in the JDK
abstract int ArkNet.Utils.ByteBuffer.GetInt32()
NOTE: This was getInt() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt32(int value)
NOTE: This was putInt() in the JDK
abstract int ArkNet.Utils.ByteBuffer.GetInt32(int index)
NOTE: This was getInt() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt32(int index, int value)
NOTE: This was putInt() in the JDK
abstract long ArkNet.Utils.ByteBuffer.GetInt64()
NOTE: This was getLong() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt64(long value)
NOTE: This was putLong() in the JDK
abstract long ArkNet.Utils.ByteBuffer.GetInt64(int index)
NOTE: This was getLong() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutInt64(int index, long value)
NOTE: This was putLong() in the JDK
abstract Int64Buffer ArkNet.Utils.ByteBuffer.AsInt64Buffer()
NOTE: This was asLongBuffer() in the JDK
abstract float ArkNet.Utils.ByteBuffer.GetSingle()
NOTE: This was getFloat() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutSingle(float value)
NOTE: This was putFloat() in the JDK
abstract float ArkNet.Utils.ByteBuffer.GetSingle(int index)
NOTE: This was getFloat() in the JDK
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutSingle(int index, float value)
NOTE: This was putFloat() in the JDK
abstract double ArkNet.Utils.ByteBuffer.GetDouble()
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutDouble(double value)
abstract double ArkNet.Utils.ByteBuffer.GetDouble(int index)
abstract ByteBuffer ArkNet.Utils.ByteBuffer.PutDouble(int index, double value)
static bool ArkNet.Utils.ByteBuffer.Equals(byte x, byte y)
static int ArkNet.Utils.ByteBuffer.Compare(byte x, byte y)