ArkNet::Utils::Int64Buffer
readonly long [] ArkNet.Utils.Int64Buffer.hb
readonly int ArkNet.Utils.Int64Buffer.offset
bool ArkNet.Utils.Int64Buffer.isReadOnly
override bool ArkNet.Utils.Int64Buffer.HasArray
override object ArkNet.Utils.Int64Buffer.Array
override int ArkNet.Utils.Int64Buffer.ArrayOffset
abstract ByteOrder ArkNet.Utils.Int64Buffer.Order
ArkNet.Utils.Int64Buffer.Int64Buffer(int mark, int pos, int lim, int cap, long[] hb, int offset)
Creates a new buffer with the given mark, position, limit, capacity, backing array, and array offset
ArkNet.Utils.Int64Buffer.Int64Buffer(int mark, int pos, int lim, int cap)
Creates a new buffer with the given mark, position, limit, and capacity
abstract Int64Buffer ArkNet.Utils.Int64Buffer.Slice()
abstract Int64Buffer ArkNet.Utils.Int64Buffer.Duplicate()
abstract Int64Buffer ArkNet.Utils.Int64Buffer.AsReadOnlyBuffer()
abstract long ArkNet.Utils.Int64Buffer.Get()
Referenced by ArkNet.Utils.Int64Buffer.CompareTo, ArkNet.Utils.Int64Buffer.Equals, ArkNet.Utils.Int64Buffer.Put.
abstract Int64Buffer ArkNet.Utils.Int64Buffer.Put(long l)
abstract long ArkNet.Utils.Int64Buffer.Get(int index)
abstract Int64Buffer ArkNet.Utils.Int64Buffer.Put(int index, long l)
virtual Int64Buffer ArkNet.Utils.Int64Buffer.Get(long[] dst, int offset, int length)
virtual Int64Buffer ArkNet.Utils.Int64Buffer.Get(long[] dst)
virtual Int64Buffer ArkNet.Utils.Int64Buffer.Put(Int64Buffer src)
References ArkNet.Utils.Int64Buffer.Get.
virtual Int64Buffer ArkNet.Utils.Int64Buffer.Put(long[] src, int offset, int length)
Int64Buffer ArkNet.Utils.Int64Buffer.Put(long[] src)
abstract Int64Buffer ArkNet.Utils.Int64Buffer.Compact()
override string ArkNet.Utils.Int64Buffer.ToString()
override int ArkNet.Utils.Int64Buffer.GetHashCode()
override bool ArkNet.Utils.Int64Buffer.Equals(object obj)
References ArkNet.Utils.Int64Buffer.Get, ArkNet.Utils.Buffer.Limit, ArkNet.Utils.Buffer.Remaining.
int ArkNet.Utils.Int64Buffer.CompareTo(Int64Buffer other)
References ArkNet.Utils.Int64Buffer.Get, ArkNet.Utils.Buffer.Position.
static Int64Buffer ArkNet.Utils.Int64Buffer.Allocate(int capacity)
static Int64Buffer ArkNet.Utils.Int64Buffer.Wrap(long[] array, int offset, int length)
static Int64Buffer ArkNet.Utils.Int64Buffer.Wrap(long[] array)
static bool ArkNet.Utils.Int64Buffer.Equals(long x, long y)
static int ArkNet.Utils.Int64Buffer.Compare(long x, long y)